<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $recipes = [
            [
                'name' => 'Classic Chocolate Chip Cookies',
                'description' => 'These are the perfect chewy chocolate chip cookies with crispy edges and soft centers. A family favorite that never disappoints!',
                'ingredients' => [
                    '2¼ cups all-purpose flour',
                    '1 tsp baking soda',
                    '1 tsp salt',
                    '1 cup butter, softened',
                    '¾ cup granulated sugar',
                    '¾ cup brown sugar',
                    '2 large eggs',
                    '2 tsp vanilla extract',
                    '2 cups chocolate chips',
                ],
                'steps' => [
                    'Preheat oven to 375°F (190°C)',
                    'Mix flour, baking soda, and salt in a bowl',
                    'Cream butter and both sugars until fluffy',
                    'Beat in eggs and vanilla',
                    'Gradually add flour mixture',
                    'Stir in chocolate chips',
                    'Drop rounded tablespoons on ungreased cookie sheets',
                    'Bake 9-11 minutes until golden brown',
                    'Cool on baking sheet for 2 minutes before removing',
                ],
                'author_email' => 'baker@sweetsmiles.com',
            ],
            [
                'name' => 'Homemade Pizza Dough',
                'description' => 'Perfect pizza dough recipe that yields a crispy yet chewy crust. Great for making authentic pizzas at home.',
                'ingredients' => [
                    '3½ cups bread flour',
                    '1 tsp sugar',
                    '1 envelope instant dry yeast',
                    '2 tsp kosher salt',
                    '1¼ cups warm water',
                    '2 tbsp olive oil',
                ],
                'steps' => [
                    'Combine flour, sugar, yeast, and salt in a large bowl',
                    'Make a well in center and add water and oil',
                    'Mix until a sticky dough forms',
                    'Knead on floured surface for 10 minutes',
                    'Place in oiled bowl, cover, and rise for 1 hour',
                    'Punch down and divide into 2 portions',
                    'Roll out to desired thickness',
                    'Add toppings and bake at 475°F for 12-15 minutes',
                ],
                'author_email' => 'chef@pizzapalace.com',
            ],
            [
                'name' => 'Beef and Vegetable Stew',
                'description' => 'A hearty, comforting stew perfect for cold days. Tender beef with carrots, potatoes, and herbs in a rich broth.',
                'ingredients' => [
                    '2 lbs beef chuck, cubed',
                    '3 tbsp vegetable oil',
                    '1 large onion, diced',
                    '3 cloves garlic, minced',
                    '3 tbsp tomato paste',
                    '4 cups beef broth',
                    '1 cup red wine',
                    '3 carrots, sliced',
                    '4 potatoes, cubed',
                    '2 bay leaves',
                    'Fresh thyme',
                    'Salt and pepper',
                ],
                'steps' => [
                    'Season beef with salt and pepper',
                    'Heat oil in Dutch oven and brown beef on all sides',
                    'Remove beef and set aside',
                    'Sauté onion until translucent',
                    'Add garlic and tomato paste, cook 1 minute',
                    'Add wine and scrape up browned bits',
                    'Return beef, add broth, bay leaves, and thyme',
                    'Bring to boil, then simmer covered for 1 hour',
                    'Add carrots and potatoes, simmer 45 minutes',
                    'Remove bay leaves and serve hot',
                ],
                'author_email' => 'chef@heartyhome.com',
            ],
            [
                'name' => 'Vanilla Bean Cheesecake',
                'description' => 'Rich and creamy New York style cheesecake with real vanilla bean and a graham cracker crust.',
                'ingredients' => [
                    '2 cups graham cracker crumbs',
                    '½ cup melted butter',
                    '2 lbs cream cheese, softened',
                    '1 cup sugar',
                    '4 large eggs',
                    '1 vanilla bean',
                    '1 tsp vanilla extract',
                    '½ cup sour cream',
                    '¼ cup heavy cream',
                ],
                'steps' => [
                    'Preheat oven to 325°F',
                    'Mix graham cracker crumbs with melted butter',
                    'Press into bottom of 9-inch springform pan',
                    'Beat cream cheese until smooth',
                    'Gradually add sugar, beating until fluffy',
                    'Add eggs one at a time',
                    'Scrape vanilla bean seeds and add with extract',
                    'Mix in sour cream and heavy cream',
                    'Pour over crust and bake 50-60 minutes',
                    'Cool completely, then refrigerate 4 hours',
                ],
                'author_email' => 'pastry@sweetdreams.com',
            ],
            [
                'name' => 'Thai Green Curry',
                'description' => 'Authentic Thai green curry with coconut milk, vegetables, and aromatic spices. Customize with your choice of protein.',
                'ingredients' => [
                    '2 tbsp green curry paste',
                    '1 can coconut milk',
                    '1 lb chicken thighs, sliced',
                    '2 tbsp fish sauce',
                    '1 tbsp brown sugar',
                    '1 eggplant, cubed',
                    '1 bell pepper, sliced',
                    '½ cup bamboo shoots',
                    'Thai basil leaves',
                    '2 kaffir lime leaves',
                    '1 red chili, sliced',
                    'Jasmine rice for serving',
                ],
                'steps' => [
                    'Heat thick coconut milk in wok over medium heat',
                    'Add curry paste and fry until fragrant',
                    'Add chicken and cook until no longer pink',
                    'Add remaining coconut milk, fish sauce, and sugar',
                    'Bring to simmer and add eggplant',
                    'Cook 10 minutes, then add bell pepper and bamboo shoots',
                    'Simmer until vegetables are tender',
                    'Stir in basil, lime leaves, and chili',
                    'Serve over jasmine rice',
                ],
                'author_email' => 'chef@thaispice.com',
            ],
            [
                'name' => 'Chocolate Lava Cake',
                'description' => 'Individual chocolate cakes with molten chocolate centers. Perfect dessert for chocolate lovers!',
                'ingredients' => [
                    '4 oz dark chocolate, chopped',
                    '4 tbsp butter',
                    '2 large eggs',
                    '2 tbsp granulated sugar',
                    '2 tbsp all-purpose flour',
                    'Pinch of salt',
                    'Butter for ramekins',
                    'Cocoa powder for dusting',
                    'Vanilla ice cream for serving',
                ],
                'steps' => [
                    'Preheat oven to 425°F',
                    'Butter four 6-oz ramekins and dust with cocoa',
                    'Melt chocolate and butter in microwave',
                    'Whisk eggs and sugar until thick',
                    'Stir in melted chocolate mixture',
                    'Fold in flour and salt',
                    'Divide batter among ramekins',
                    'Bake 12-14 minutes until edges are firm',
                    'Let stand 1 minute, then invert onto plates',
                    'Serve immediately with ice cream',
                ],
                'author_email' => 'pastry@chocohaven.com',
            ],
            [
                'name' => 'Mediterranean Quinoa Salad',
                'description' => 'Fresh and healthy quinoa salad with Mediterranean flavors. Perfect for meal prep or light lunches.',
                'ingredients' => [
                    '1 cup quinoa',
                    '2 cups vegetable broth',
                    '1 cucumber, diced',
                    '2 tomatoes, diced',
                    '½ red onion, finely diced',
                    '½ cup kalamata olives',
                    '½ cup feta cheese, crumbled',
                    '¼ cup fresh parsley',
                    '2 tbsp fresh mint',
                    '3 tbsp olive oil',
                    '2 tbsp lemon juice',
                    '1 tsp oregano',
                    'Salt and pepper',
                ],
                'steps' => [
                    'Rinse quinoa under cold water',
                    'Cook quinoa in vegetable broth until tender',
                    'Let quinoa cool completely',
                    'Dice cucumber, tomatoes, and red onion',
                    'Chop fresh herbs',
                    'Whisk together oil, lemon juice, and oregano',
                    'Combine quinoa with vegetables and herbs',
                    'Add feta cheese and olives',
                    'Toss with dressing and season with salt and pepper',
                    'Chill for at least 30 minutes before serving',
                ],
                'author_email' => 'healthy@medkitchen.com',
            ],
            [
                'name' => 'Classic French Onion Soup',
                'description' => 'Traditional French onion soup with caramelized onions in rich beef broth, topped with Gruyère cheese.',
                'ingredients' => [
                    '6 large yellow onions, sliced',
                    '4 tbsp butter',
                    '2 tbsp olive oil',
                    '1 tsp sugar',
                    '1 tsp salt',
                    '4 cups beef broth',
                    '2 cups chicken broth',
                    '½ cup dry white wine',
                    '2 bay leaves',
                    'Fresh thyme',
                    '6 slices French bread',
                    '1½ cups Gruyère cheese, grated',
                ],
                'steps' => [
                    'Heat butter and oil in large pot',
                    'Add onions, sugar, and salt',
                    'Cook onions slowly for 45 minutes until caramelized',
                    'Add wine and cook 2 minutes',
                    'Add broths, bay leaves, and thyme',
                    'Simmer 30 minutes',
                    'Toast bread slices',
                    'Ladle soup into oven-safe bowls',
                    'Top with bread and cheese',
                    'Broil until cheese is bubbly and golden',
                ],
                'author_email' => 'chef@frenchbistro.com',
            ],
            [
                'name' => 'Banana Bread',
                'description' => 'Moist and delicious banana bread made with ripe bananas and a hint of cinnamon. Perfect for breakfast or snacking.',
                'ingredients' => [
                    '3 ripe bananas, mashed',
                    '⅓ cup melted butter',
                    '¾ cup sugar',
                    '1 egg, beaten',
                    '1 tsp vanilla extract',
                    '1 tsp baking soda',
                    'Pinch of salt',
                    '1½ cups all-purpose flour',
                    '½ tsp cinnamon',
                    '½ cup chopped walnuts (optional)',
                ],
                'steps' => [
                    'Preheat oven to 350°F',
                    'Grease a 4x8 inch loaf pan',
                    'Mix melted butter with mashed bananas',
                    'Stir in sugar, egg, and vanilla',
                    'Sprinkle baking soda and salt over mixture',
                    'Add flour and cinnamon, mix until just combined',
                    'Fold in walnuts if using',
                    'Pour into prepared loaf pan',
                    'Bake 60-65 minutes until toothpick comes out clean',
                    'Cool in pan for 10 minutes before removing',
                ],
                'author_email' => 'baker@homecomfort.com',
            ],
            [
                'name' => 'Chicken Alfredo Pasta',
                'description' => 'Creamy chicken alfredo with perfectly cooked fettuccine in a rich parmesan sauce.',
                'ingredients' => [
                    '1 lb fettuccine pasta',
                    '2 chicken breasts',
                    '4 tbsp butter',
                    '3 cloves garlic, minced',
                    '1 cup heavy cream',
                    '1 cup freshly grated Parmesan cheese',
                    '½ cup chicken broth',
                    '2 tbsp olive oil',
                    'Salt and pepper',
                    'Fresh parsley',
                    'Red pepper flakes (optional)',
                ],
                'steps' => [
                    'Season chicken with salt and pepper',
                    'Heat olive oil in large skillet',
                    'Cook chicken until golden and cooked through',
                    'Remove chicken and slice into strips',
                    'Cook pasta according to package directions',
                    'In same skillet, melt butter and sauté garlic',
                    'Add cream and chicken broth, simmer',
                    'Stir in Parmesan cheese until melted',
                    'Add pasta and chicken to sauce',
                    'Toss until well coated, garnish with parsley',
                ],
                'author_email' => 'chef@italianclassic.com',
            ],
        ];

        foreach ($recipes as $recipeData) {
            // Remove slug if present since model events will handle it
            unset($recipeData['slug']);
            Recipe::create($recipeData);
        }
    }
}
