<?php

namespace Database\Factories;

use App\Models\Recipe;
use Illuminate\Database\Eloquent\Factories\Factory;

class RecipeFactory extends Factory
{
    protected $model = Recipe::class;

    public function definition(): array
    {
        $name = $this->faker->words(3, true);

        return [
            'name' => ucwords($name),
            'description' => $this->faker->paragraph(2),
            // slug is auto-generated by the Recipe model
            'image_url' => $this->faker->optional()->imageUrl(640, 480, 'food'),
            'prep_time' => $this->faker->optional()->numberBetween(5, 60),
            'cook_time' => $this->faker->optional()->numberBetween(10, 180),
            'servings' => $this->faker->optional()->numberBetween(1, 8),
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }

    /**
     * Create a recipe with complete relationships.
     */
    public function complete()
    {
        return $this->afterCreating(function (Recipe $recipe) {
            // Create a default author
            $recipe->authors()->create([
                'name' => $this->faker->name,
                'email' => $this->faker->unique()->safeEmail,
                'about' => $this->faker->optional()->paragraph,
            ]);

            // Create ingredients
            $ingredientCount = $this->faker->numberBetween(3, 6);
            $commonIngredients = [
                'flour', 'sugar', 'butter', 'eggs', 'milk', 'vanilla extract',
                'baking powder', 'salt', 'olive oil', 'garlic', 'onion',
                'tomatoes', 'cheese', 'chicken', 'beef', 'rice', 'pasta',
                'herbs', 'spices', 'lemon', 'pepper', 'cream',
                'carrots', 'potatoes', 'broth', 'wine', 'bread crumbs',
            ];

            $selectedIngredients = $this->faker->randomElements($commonIngredients, $ingredientCount);
            foreach ($selectedIngredients as $ingredient) {
                $recipe->ingredients()->create([
                    'name' => $ingredient,
                    'quantity' => $this->faker->randomFloat(2, 0.5, 5),
                    'unit' => $this->faker->optional()->randomElement(['cups', 'tbsp', 'tsp', 'oz', 'lbs', 'g', 'kg', 'ml', 'l']),
                ]);
            }

            // Create steps
            $stepCount = $this->faker->numberBetween(3, 6);
            $stepTemplates = [
                'Preheat oven to temperature',
                'Mix dry ingredients in a large bowl',
                'Combine wet ingredients separately',
                'Gradually add wet ingredients to dry ingredients',
                'Pour mixture into prepared pan',
                'Bake until golden brown',
                'Let cool before serving',
                'Heat oil in a large pan',
                'Add vegetables and cook until tender',
                'Season with salt and pepper to taste',
                'Simmer until flavors combine',
                'Serve hot and enjoy',
            ];

            $selectedSteps = $this->faker->randomElements($stepTemplates, $stepCount);
            foreach ($selectedSteps as $index => $step) {
                $recipe->steps()->create([
                    'title' => $this->faker->optional()->sentence(3),
                    'description' => $step,
                    'order' => $index + 1,
                ]);
            }
        });
    }

    /**
     * Create a recipe with only authors.
     */
    public function withAuthors(int $count = 1)
    {
        return $this->afterCreating(function (Recipe $recipe) use ($count) {
            for ($i = 0; $i < $count; $i++) {
                $recipe->authors()->create([
                    'name' => $this->faker->name,
                    'email' => $this->faker->unique()->safeEmail,
                    'about' => $this->faker->optional()->paragraph,
                ]);
            }
        });
    }

    public function withName(string $name): self
    {
        return $this->state([
            'name' => $name,
        ]);
    }
}
