<?php

namespace Database\Factories;

use App\Models\Recipe;
use Illuminate\Database\Eloquent\Factories\Factory;
use FakerRestaurant\Provider\en_US\Restaurant;

class RecipeFactory extends Factory
{
    protected $model = Recipe::class;

    /**
     * Configure the factory's faker instance.
     */
    public function configure()
    {
        return $this->afterMaking(function (Recipe $recipe) {
            // Add the FakerRestaurant provider
            $this->faker->addProvider(new Restaurant($this->faker));
        });
    }

    public function definition(): array
    {
        // Add the FakerRestaurant provider for this instance
        $this->faker->addProvider(new Restaurant($this->faker));

        // Generate more realistic recipe names using combinations
        $nameOptions = [
            // Using FakerRestaurant methods
            fn() => $this->faker->randomElement(['Classic', 'Homemade', 'Traditional', 'Modern', 'Gourmet']) . ' ' . $this->faker->foodName(),
            fn() => $this->faker->meatName() . ' with ' . $this->faker->vegetableName(),
            fn() => $this->faker->randomElement(['Grilled', 'Roasted', 'Baked', 'Fried', 'Steamed']) . ' ' . $this->faker->meatName(),
            fn() => $this->faker->vegetableName() . ' ' . $this->faker->randomElement(['Salad', 'Soup', 'Stir-fry', 'Curry', 'Stew']),
            fn() => $this->faker->sauceName() . ' ' . $this->faker->randomElement(['Pasta', 'Chicken', 'Fish', 'Vegetables']),
            fn() => $this->faker->fruitName() . ' ' . $this->faker->randomElement(['Pie', 'Tart', 'Smoothie', 'Salad', 'Cake']),
            fn() => $this->faker->dairyName() . ' ' . $this->faker->randomElement(['Sauce', 'Dip', 'Spread', 'Soup']),
            fn() => $this->faker->beverageName() . ' ' . $this->faker->randomElement(['Cocktail', 'Mocktail', 'Smoothie', 'Shake']),
        ];

        $name = $this->faker->randomElement($nameOptions)();

        // Generate image URLs with better sources
        $imageSource = $this->faker->randomElement(['picsum', 'loremflickr']);
        $imageUrl = $imageSource === 'loremflickr'
            ? "https://loremflickr.com/640/480/food,recipe,cooking"
            : "https://picsum.photos/640/480?random=" . rand(1, 10000);

        return [
            'name' => ucwords($name),
            'description' => $this->faker->paragraph(2),
            'category' => $this->faker->randomElement(config('recipes.categories', [])),
            // slug is auto-generated by the Recipe model
            'image_url' => $imageUrl,
            'prep_time' => $this->faker->numberBetween(5, 60),
            'cook_time' => $this->faker->numberBetween(10, 180),
            'servings' => $this->faker->numberBetween(1, 12),
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }

    /**
     * Create a recipe with complete relationships.
     */
    public function complete(array $options = [])
    {
        return $this->afterCreating(function (Recipe $recipe) use ($options) {
            // Add the FakerRestaurant provider
            $this->faker->addProvider(new Restaurant($this->faker));

            // Extract options with defaults
            $minAuthors = $options['min_authors'] ?? 1;
            $maxAuthors = $options['max_authors'] ?? 2;
            $minIngredients = $options['min_ingredients'] ?? 3;
            $maxIngredients = $options['max_ingredients'] ?? 12;
            $minSteps = $options['min_steps'] ?? 3;
            $maxSteps = $options['max_steps'] ?? 10;

            // Create authors
            $authorCount = $this->faker->numberBetween($minAuthors, $maxAuthors);
            for ($i = 0; $i < $authorCount; $i++) {
                $recipe->authors()->create([
                    'name' => $this->faker->name,
                    'email' => $this->faker->unique()->safeEmail,
                    'about' => $this->faker->optional(0.7)->text(100),
                ]);
            }

            // Create ingredients using FakerRestaurant
            $ingredientCount = $this->faker->numberBetween($minIngredients, $maxIngredients);
            $usedIngredients = [];

            for ($i = 0; $i < $ingredientCount; $i++) {
                // Generate unique ingredient using FakerRestaurant methods
                $ingredientOptions = [
                    fn() => $this->faker->vegetableName(),
                    fn() => $this->faker->meatName(),
                    fn() => $this->faker->fruitName(),
                    fn() => $this->faker->dairyName(),
                    fn() => $this->faker->sauceName(),
                    fn() => $this->faker->randomElement(['salt', 'pepper', 'sugar', 'flour', 'eggs', 'butter', 'olive oil', 'garlic', 'onion', 'herbs', 'spices', 'vanilla extract', 'baking powder', 'baking soda', 'yeast', 'vinegar', 'honey', 'rice', 'pasta', 'bread crumbs', 'stock', 'wine']),
                ];

                do {
                    $ingredient = $this->faker->randomElement($ingredientOptions)();
                } while (in_array(strtolower($ingredient), $usedIngredients));

                $usedIngredients[] = strtolower($ingredient);

                // Determine appropriate units based on ingredient type
                $units = ['cups', 'tbsp', 'tsp', 'lbs', 'oz', 'g', 'kg', 'ml', 'l', 'cloves', 'slices', 'pieces', null];

                $recipe->ingredients()->create([
                    'name' => $ingredient,
                    'quantity' => $this->faker->randomFloat(2, 0.25, 4),
                    'unit' => $this->faker->randomElement($units),
                ]);
            }

            // Create steps with more realistic cooking instructions
            $stepCount = $this->faker->numberBetween($minSteps, $maxSteps);
            $stepTitles = [
                'Prepare ingredients', 'Preheat oven', 'Mix dry ingredients', 'Combine wet ingredients',
                'Heat oil', 'Sauté vegetables', 'Add seasoning', 'Simmer', 'Bake', 'Cool', 'Serve',
                'Chop vegetables', 'Marinate', 'Grill', 'Boil water', 'Drain', 'Garnish', 'Chill',
                'Brown meat', 'Deglaze pan', 'Reduce heat', 'Stir continuously', 'Rest', 'Slice',
                'Whisk', 'Fold gently', 'Steam', 'Blanch', 'Sear', 'Roast', 'Broil', 'Toast'
            ];

            for ($i = 0; $i < $stepCount; $i++) {
                $title = ($i === 0)
                    ? $this->faker->randomElement(['Prepare ingredients', 'Preheat oven', 'Heat oil', 'Prep work'])
                    : $this->faker->randomElement($stepTitles);

                $recipe->steps()->create([
                    'title' => $title,
                    'description' => $this->faker->sentence(10),
                    'order' => $i + 1,
                ]);
            }
        });
    }

    /**
     * Create a recipe with only authors.
     */
    public function withAuthors(int $count = 1)
    {
        return $this->afterCreating(function (Recipe $recipe) use ($count) {
            for ($i = 0; $i < $count; $i++) {
                $recipe->authors()->create([
                    'name' => $this->faker->name,
                    'email' => $this->faker->unique()->safeEmail,
                    'about' => $this->faker->optional()->paragraph,
                ]);
            }
        });
    }

    public function withName(string $name): self
    {
        return $this->state([
            'name' => $name,
        ]);
    }
}
